### ISSUE TITLE
some titles do not provide URL for digital source

### ISSUE THREAD

**Issue by lb42** [COST-ELTeC/ELTeC-por#2]
Most `<bibl type='digitalSource'>` contain a `<ref>` supplying the URL for the digital source (79 by my count). But there remain 21 for which only text (in the `<publisher>`)  is supplied.

**Comment by dianamsmpsantos** [comment]
Dear Lou
Those cases are the ones that were digitalized for us by the National
Library of Portugal. I put them as digital source because I expect they
will also be put available for the general public there.
But I understand now that either I get the URL from them, or it makes no
sense.
I've just asked them if they have made them available.
Best,
Diana

Lou <notifications@github.com> escreveu no dia domingo, 7/06/2020 à(s)
14:02:

**Comment by lb42** [comment]
Most of them are indeed from the National Library; I see three which are not, though: POR0077 (Wikimedia); POR0066 (Bibliotronica); POR0008 (Project Gutenberg!)

**Comment by dianamsmpsantos** [comment]
Thank you, these have been corrected. Could you please see ig the title
pages of the three are as they should? Thanks a lot in advance

Lou <notifications@github.com> escreveu no dia domingo, 7/06/2020 à(s)
17:40:

**Comment by lb42** [comment]
There are still just three cases where the `<ref>` does not have a valid value:
   POR0006
   POR0065
   POR0075
The PURL is ok, but you need to prefix it with "http://purl.pt"  in each case

**Comment by dianamsmpsantos** [comment]
Dear Lou, I changed the reference, hope they are ok now :)
Happy New year!
Diana

Lou <notifications@github.com> escreveu no dia domingo, 3/01/2021 à(s)
18:38:

**Comment by lb42** [comment]
All looks fine now so closing this.
